version: "3"
services:
  postgres:
    build:
      context: ./
      dockerfile: docker_files/Dockerfile.db
    ports:
      - '5432:5432'
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - global_atomizer_pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - global_atomizer_redis_data:/redis:/data
    environment:
      - REDIS_DATABASES=2
  web:
    build:
      context: ./
      dockerfile: ./docker_files/Dockerfile.wagtail.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - static_volume:/home/static
      - media_volume:/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  global_atomizer_pg_data:
  global_atomizer_redis_data:
  static_volume:
  media_volume:
