# Generated by Django 4.2 on 2024-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
