# Generated by Django 4.2 on 2024-03-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tariffs_tgbotsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tariffs', verbose_name='Tariff'),
        ),
    ]
