# Generated by Django 4.2 on 2024-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tariffs_description_en_tariffs_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='en', max_length=4),
        ),
    ]
