# Generated by Django 4.2 on 2024-03-19 17:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='terms_of_use_text',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Terms of use text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='terms_of_use_text_en',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Terms of use text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='terms_of_use_text_ru',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Terms of use text'),
        ),
    ]
