# Generated by Django 4.2 on 2024-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tgbotsnippet_donate_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='donate_btn_text_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Donate button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='donate_btn_text_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Donate button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='settings_btn_text_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Settings button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='settings_btn_text_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Settings button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='tariffs_btn_text_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Tariffs button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='tariffs_btn_text_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Tariffs button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='web_app_btn_text_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Web app button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='web_app_btn_text_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Web app button text'),
        ),
    ]
