# Generated by Django 4.2 on 2024-03-20 16:44

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tgbotsnippet_donate_btn_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='language_choice_text',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Language choice text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='language_choice_text_en',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Language choice text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='language_choice_text_ru',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Language choice text'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='currency',
            field=models.IntegerField(choices=[(1, 'Ruble ₽'), (2, 'Euro €'), (3, 'Dollar $')], verbose_name='Currency tariff'),
        ),
    ]
