# Generated by Django 4.2 on 2024-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tgbotsnippet_language_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='back_btn_text',
            field=models.CharField(max_length=32, null=True, verbose_name='Back button text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='home_btn_text',
            field=models.CharField(max_length=32, null=True, verbose_name='Home button text'),
        ),
    ]
