# Generated by Django 4.2 on 2024-03-20 18:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tgbotsnippet_back_btn_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='tariff_choice_text',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Tariff choice text'),
        ),
    ]
