# Generated by Django 4.2 on 2024-03-20 18:07

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tgbotsnippet_tariff_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='tariff_choice_text_en',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Tariff choice text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='tariff_choice_text_ru',
            field=wagtail.fields.RichTextField(null=True, verbose_name='Tariff choice text'),
        ),
    ]
