# Generated by Django 4.2 on 2024-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tgbotsnippet_tariff_choice_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='buy_tariff_btn',
            field=models.CharField(max_length=32, null=True, verbose_name='Buy tariff button'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='buy_tariff_btn_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Buy tariff button'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='buy_tariff_btn_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Buy tariff button'),
        ),
    ]
