# Generated by Django 4.2 on 2024-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_tgbotsnippet_buy_tariff_btn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffs',
            name='currency',
            field=models.IntegerField(choices=[(1, 'RUB'), (2, 'EUR'), (3, 'USD')], verbose_name='Currency tariff'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tariff price'),
        ),
    ]
