# Generated by Django 4.2 on 2024-03-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_tgbotsnippet_description_tgbotsnippet_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgbotsnippet',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tgbotsnippet',
            name='description_ru',
        ),
    ]
