# Generated by Django 4.2 on 2024-03-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0021_tgbotsnippet_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbotsnippet',
            name='about_bot',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot about text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='about_bot_en',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot about text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='about_bot_ru',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot about text'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='bot_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bot image'),
        ),
        migrations.AddField(
            model_name='tgbotsnippet',
            name='description_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bot description image'),
        ),
        migrations.AlterField(
            model_name='tgbotsnippet',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot description text'),
        ),
        migrations.AlterField(
            model_name='tgbotsnippet',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot description text'),
        ),
        migrations.AlterField(
            model_name='tgbotsnippet',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='Bot description text'),
        ),
    ]
