# Generated by Django 4.2 on 2024-03-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_tgbotsnippet_about_bot_tgbotsnippet_about_bot_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgbotsnippet',
            name='bot_image',
        ),
        migrations.RemoveField(
            model_name='tgbotsnippet',
            name='description_image',
        ),
    ]
