# Generated by Django 4.2 on 2024-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_tgbotsnippet_bot_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Telegram first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Telegram last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(max_length=64, null=True, verbose_name='Telegram Username'),
        ),
    ]
