# Generated by Django 4.2 on 2024-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homepage_alter_tgbotsnippet_main_menu_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Test'),
        ),
    ]
